package pgkn.pages

import com.raquo.laminar.api.L.*
import com.raquo.waypoint.*
import pgkn.components.NavHeader
import pgkn.components.SvgIcon

object KaptenAlloc:
  def apply(router: Router[pgkn.Page]): HtmlElement =
    mainTag(
      className := "kapten-alloc-page",
      NavHeader(router),
      div(
        className := "kapten-alloc-page-content",
        div(
          className := "kapten-alloc-subheader",
          sectionTag(
            input(
              typ := "text",
              placeholder := "Sök..."
            )
          ),
          sectionTag(
            a(
              span("TimeEdit"),
              SvgIcon("/icons/externalLink.svg")
            ),
            a(
              span("Karta"),
              SvgIcon("/icons/externalLink.svg")
            )
          ),
          sectionTag(
            button(
              span("Ladda ner"),
              SvgIcon("/icons/download.svg")
            )
          )
        ),
        div(
          className := "kapten-alloc-table-container",
          table(
            className := "kapten-alloc-table",
            thead(
              tr(
                th("Typ"),
                th("Datum"),
                th("Vecka"),
                th("Dag"),
                th("Tid"),
                th("Grupp"),
                th("Rum"),
                th("Vem?")
              )
            ),
            tbody(
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.01"),
                td("Elg"),
                td("SAR")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.02"),
                td("Hacke"),
                td("SAJ")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.03"),
                td("Panter"),
                td("ALW")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.04"),
                td("Ravel"),
                td("JUG")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.09"),
                td("Falk"),
                td("ELÅ")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.10"),
                td("Val"),
                td("NAK")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.11"),
                td("Varg"),
                td("WIS")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.12"),
                td("Alfa"),
                td("MAU")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.13"),
                td("Beta"),
                td("MOJ")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("D1.14"),
                td("Gamma"),
                td("AXF")
              ),
              tr(
                td("Resurstid"),
                td("2025-09-03"),
                td("v36"),
                td("ons"),
                td("15:15"),
                td("XA1"),
                td("Ambulans"),
                td("MEW")
              ),
              tr(
                td("DodLabb"),
                td("2025-09-04"),
                td("v36"),
                td("tor"),
                td("10:15"),
                td("C1.01"),
                td("Alfa"),
                td("JOE")
              ),
              tr(
                td("DodLabb"),
                td("2025-09-04"),
                td("v36"),
                td("tor"),
                td("10:15"),
                td("C1.02"),
                td("Beta"),
                td("APR")
              ),
              tr(
                td("DodLabb"),
                td("2025-09-04"),
                td("v36"),
                td("tor"),
                td("10:15"),
                td("C1.03"),
                td("Gamma"),
                td("JON")
              )
            )
          )
        )
      ),
      div(
        className := "kapten-alloc-controls",
        p("Controls will go here")
      )
    )
